### ISSUE TITLE
Modifying introductory content markup before form source code is generated

### ISSUE THREAD

**Issue by wilsond-gds** [HMPO/hmpo-form-wizard#184]
**Problem**: We have a separate page called the 'passport escape' that users can reach from the main form in our HMPO app - sample url is here: https://review-p.integration.account.gov.uk/passport/prove-another-way. For our google analytics collection to work correctly, the `<h1>` on this page needs to have a custom class added to it

**Attempted solution**: I've tried overriding the `{% block mainContent %}` for the prove-another-way page to manually build the page content and add the class to the `<h1>`

**Issue**: This creates the correct source code for the content, but the form (boxed in pink in the screenshot) under the content disappears. How do we override the html attributes for the source code created from the yaml file for the content while also creating the form markup in the HMPO app?

![Screenshot 2022-07-25 at 14 22 39](https://user-images.githubusercontent.com/101639632/180788518-764bb102-c6a4-4412-9f57-0710b892f64b.png)

**Comment by HughePaul** [comment]
You should be able to set the localisation for the h1/title and the content block and it should render it as above, eg:
```
pages:
  prove-another-way:
    title: Prove your identity another way
    content:
    - You must have a UK passport to prove etc etc
    - This might take you longer than 10 minutes.
```
